mmitem:
  yukiti_ticket:
    sellprice: 10000
  itiyou_ticket:
    sellprice: 5000
  syurei_ticket:
    sellprice: 2000
  noguti_ticket:
    sellprice: 1000
  assyukuwheat:
    sellprice: 1920
  assyukupotato:
    sellprice: 1920
  assyukucarrot:
    sellprice: 1920
  assyukuspruce:
    sellprice: 640
  assyukunether:
    sellprice: 320
  assyukuend:
    sellprice: 640
SellItemDisplay: "----------------------------\n[smg 販売リスト]
\n&3一万円&r,&3五千円&r
\n&3二千円&r,&3千円&r
\n圧縮小麦チケット,圧縮ポテトチケット
\n圧縮人参チケット,圧縮松の木チケット
\n圧縮ネザーラックチケット,圧縮エンドストーンチケット
\n----------------------------"